---
title: "Hourly Energy Demand in Ontario 2003-2015"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
# runtime: shiny
---

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(shiny)
library(readxl)
library(lubridate)
library(plyr)
library(dplyr)
library (ggplot2)
library(GGally)
library(ggstatsplot)
```


```{r data, echo=FALSE}

df_dm <- read_excel('ssc2020_hourly_demand.xlsx', sheet = 2) 
df_wt <- read_excel('ssc2020_hourly_weather.xlsx', sheet = 2) 

df_dm$Date <- format.Date(df_dm$Date, "%Y-%m-%d")

df_wt$formatted_time <- as.numeric(format(df_wt$time, "%H")) + 1
df_wt$formatted_date <- format.Date(df_wt$time, "%Y-%m-%d")

df <- merge(x=df_dm, y=df_wt, by.x = c("Date", "Hour"), 
            by.y = c("formatted_date", "formatted_time"))

colnames(df)[3] <- 'Energy'

test <- df[ df$Year < 2016 ,]
#which(test$Energy<10000)

df2 <- test[-c(5407, 5408, 5409, 5410, 5412, 5413, 5414, 
             5415, 5416, 5424, 5435, 5441, 5442, 5443, 5444),]
                    
```

Energy (1)
===
Row {data-width=100}
--------------------------------------
### Average Hourly Energy Use From Electricity (MW)
```{r, echo=FALSE}
elect_bar <- round((mean(df$Energy)), digits = 0)
valueBox(value = elect_bar,icon = "ion-ios-bolt",
         caption = "Average Hourly Energy Demand (MW)",color = "orange")
```

### Max Hourly Energy Use From Electricity (MW)
```{r, echo = FALSE}
elect_bar <- round(max(df$Energy), digits = 0)
valueBox(value = elect_bar,icon = "ion-ios-bolt",
         caption = "Maximum Hourly Energy Demand (MW)",color = "blue")
```

Row {data-width=400}
-----------------------------------------------------------------------
### Annual Energy Distribution 
```{r, echo=FALSE}
boxplot <- df %>% filter(Year < 2016) %>% 
  ggplot() + 
  geom_violin(aes(x = as.factor(Year), y = Energy), color ="lightsteelblue1",
              fill="royalblue", alpha = 0.2) +
  geom_boxplot(aes(x = as.factor(Year), y = Energy), color = "chocolate1",
               fill="tan1", width=0.4)
boxplot +
  scale_x_discrete(name = "Year") + 
  scale_y_continuous(breaks = c(0, 10000, 20000, 30000), 
                     labels = c("0 K", "10 K", "20 K", "30 K"),
                     limits=c(1000,30000), name = "Energy (MWh)") + 
  scale_fill_manual(values = c("#90C432","#2494b5")) +
  theme(panel.grid.major = element_line(colour = "gray", linetype = "dotted"), 
        panel.grid.minor = element_line(linetype = "blank"), 
        axis.title = element_text(size = 15,colour = "black"), 
        axis.text = element_text(colour = "black",size = 10), 
        panel.background = element_rect(fill = "white"), 
        plot.background = element_rect(colour = NA))

```

### Monthly Energy Distribution
```{r, echo=FALSE}
boxplot <- df %>% filter(Year < 2016) %>% 
  ggplot() +
  geom_violin(aes(x = as.factor(Month), y = Energy), color ="lightsteelblue1",
              fill="royalblue", alpha = 0.2) +
  geom_boxplot(aes(x = as.factor(Month), y = Energy), color = "violetred",
               fill="plum2",
               width=0.3)
boxplot +
  scale_x_discrete(breaks = seq_along(month.name), 
                   labels = month.abb[1:12], 
                   name = "Month") + 
  scale_y_continuous(breaks = c(0, 10000, 20000, 30000), 
                     labels = c("0 K", "10 K", "20 K", "30 K"),
                     limits=c(1000,30000), name = "Energy (MWh)") + 
  scale_fill_manual(values = c("#90C432","#2494b5")) +
  theme(panel.grid.major = element_line(colour = "gray", linetype = "dotted"), 
        panel.grid.minor = element_line(linetype = "blank"), 
        axis.title = element_text(size = 15,colour = "black"), 
        axis.text = element_text(colour = "black",size = 10), 
        panel.background = element_rect(fill = "white"), 
        plot.background = element_rect(colour = NA))
```

### Hourly Energy Distribution
```{r, echo=FALSE}
boxplot <- df %>% filter(Year < 2016) %>% 
  ggplot() + 
  geom_violin(aes(x = as.factor(Hour), y = Energy), color ="lightsteelblue1",
              fill="royalblue", alpha = 0.2) +
  geom_boxplot(aes(x = as.factor(Hour), y = Energy), 
               color = "dodgerblue4", width=0.3)

boxplot +
  scale_x_discrete(name = "Hour") + 
  scale_y_continuous(breaks = c(0, 10000, 20000, 30000), 
                     labels = c("0 K", "10 K", "20 K", "30 K"),
                     limits=c(1000,30000), name = "Energy (MWh)") + 
  scale_fill_manual(values = c("#90C432","#2494b5")) +
  theme(panel.grid.major = element_line(colour = "gray", linetype = "dotted"), 
        panel.grid.minor = element_line(linetype = "blank"), 
        axis.title = element_text(size = 15,colour = "black"), 
        axis.text = element_text(colour = "black",size = 10), 
        panel.background = element_rect(fill = "white"), 
        plot.background = element_rect(colour = NA))
```


Energy (2)
===

Row
-----------------------------------------------------------------------
### Four Seasons
```{r, echo=FALSE}
graph <- function(data, mapping){
  p <- ggplot(data = data, mapping = mapping) + 
    geom_point(alpha = 0.5, color = "blue") + 
    geom_smooth(method = "lm", formula = y~x, col = 'red')
  p
}

df2$saison <- ifelse(df2$Month %in% c(12, 1, 2, 3), 
                     'winter', 
                     ifelse(df2$Month %in% c(4, 5), 
                            'spring', 
                            ifelse(df2$Month %in% c(6, 7, 8), 
                                   'summer', 
                                   'fall'
                            )
                     )
)

df2$saison_color <- ifelse(df2$saison == "winter",
                           "blue",
                           ifelse(df2$saison == "spring",
                                  "darkgreen",
                                  ifelse(df2$saison == "summer",
                                         "red",
                                         "orange"
                                  )
                           )
)

plot_saisons <- function(df) {
  df <- arrange(df, saison)
  p1 <- ggplot(df, aes(x=Hour, y=Energy)) + 
    stat_summary(fun=mean, geom = "line", aes(col=saison_color), lwd=1.1) + 
    scale_x_continuous(breaks = seq(0, 24, 6), name = "Hour") + 
    scale_y_continuous(breaks = c(14000, 16000, 18000, 20000), 
                       labels = c("14 K", "16 K", "18 K", "20 K"),
                       name = "Energy (MWh)") +
    scale_color_identity(labels = c("winter", "spring", "summer", "fall"), 
                         guide = 'legend') + 
    labs(color = 'Season') + 
    theme(legend.title = element_text(size=10), 
          legend.text = element_text(size=8),
          axis.title = element_text(size = 12,colour = "black"), 
          axis.text = element_text(colour = "black",size = 10)
    )
  print(p1)
}

plot_saisons(df2)
```

### Two Periods: November - April & May - October
```{r, echo=FALSE}
df2$saison <- ifelse(df2$Month %in% c(11, 12, 1, 2, 3, 4), 
                     'november - april', 
                     'may - october'
                      )

df2$saison_color <- ifelse(df2$saison == "november - april",
                           "#542DD2",
                           "#ABD22D"
                          )

plot_saisons <- function(df) {
  df <- arrange(df, saison)
  p1 <- ggplot(df, aes(x=Hour, y=Energy)) + 
    stat_summary(fun=mean, geom = "line", aes(col=saison_color), lwd=1.1) + 
   
    scale_x_continuous(breaks = seq(0, 24, 6), name = "Hour") + 
    scale_y_continuous(breaks = c(14000, 16000, 18000, 20000), 
                       labels = c("14 K", "16 K", "18 K", "20 K"),
                       name = "Energy (MWh)") +
    scale_color_identity(labels = c("november - april", "may - october"),  
                         guide = 'legend') + 
    labs(color = 'Period') + 
    theme(legend.title = element_text(size=10), 
          legend.text = element_text(size=8),
          axis.title = element_text(size = 12,colour = "black"), 
          axis.text = element_text(colour = "black",size = 10) 
    )
  print(p1)
}

plot_saisons(df2)
```


Temperature
===
Row {data-width=100}
--------------------------------------
### Average Temperature (°C)
```{r, echo=FALSE}
temp_bar <- round(mean(df2$temperature), digits = 2)
valueBox(value = temp_bar,icon = "ion-ios-partlysunny",
         caption = "Average Temperature (°C)",color = "orange")
```

### Max Temperature (°C)
```{r, echo = FALSE}
tempmax <- round(max(df2$temperature), digits = 2)
valueBox(value = tempmax,icon = "ion-ios-partlysunny",
         caption = "Maximum Temperature (°C)",color = "blue")
```

### Min Temperature (°C)
```{r, echo = FALSE}
tempmin <- round(min(df2$temperature), digits = 2)
valueBox(value = tempmin,icon = "ion-ios-partlysunny",
         caption = "Minimum Temperature (°C)",color = "green")
```

Row
-----------------------------------------------------------------------
### Annual Temperature Distribution 

```{r, echo=FALSE}
boxplot <- df2 %>% filter(Year < 2016) %>% 
  ggplot() + 
  geom_violin(aes(x = as.factor(Year), y = temperature), 
              color ="lightsteelblue1",
              fill="lightsteelblue1", alpha = 0.2) +
  geom_boxplot(aes(x = as.factor(Year), y = temperature), 
               color = "firebrick2",
               fill="orange", width=0.3)
boxplot +
  scale_x_discrete(name = "Year") + 
  scale_y_continuous(limits=c(-40,40), name = "Temperature (°C)") + 
  scale_fill_manual(values = c("#90C432","#2494b5")) +
  theme(panel.grid.major = element_line(colour = "gray", linetype = "dotted"), 
        panel.grid.minor = element_line(linetype = "blank"), 
        axis.title = element_text(size = 15,colour = "black"), 
        axis.text = element_text(colour = "black",size = 10), 
        panel.background = element_rect(fill = "white"), 
        plot.background = element_rect(colour = NA))

```

### Monthly Temperature Distribution

```{r, echo=FALSE}
boxplot <- df2 %>% filter(Year < 2016) %>% 
  ggplot() + 
  geom_violin(aes(x = as.factor(Month), y = temperature), 
              color ="lightsteelblue1",
              fill="lightsteelblue1", alpha = 0.2) +
  geom_boxplot(aes(x = as.factor(Month), y = temperature), 
               color = "firebrick2",
               fill="orange",
               width=0.3)
boxplot +
  scale_x_discrete(breaks = seq_along(month.name), 
                   labels = month.abb[1:12], 
                   name = "Month") + 
  scale_y_continuous(limits=c(-40,40), name = "Temperature (°C)") + 
  scale_fill_manual(values = c("#90C432","#2494b5")) +
  theme(panel.grid.major = element_line(colour = "gray", linetype = "dotted"), 
        panel.grid.minor = element_line(linetype = "blank"), 
        axis.title = element_text(size = 15,colour = "black"), 
        axis.text = element_text(colour = "black",size = 10), 
        panel.background = element_rect(fill = "white"), 
        plot.background = element_rect(colour = NA))
```

### Hourly Temperature Distribution

```{r, echo=FALSE}
boxplot <- df2 %>% filter(Year < 2016) %>% 
  ggplot() + 
  geom_violin(aes(x = as.factor(Hour), y = temperature), 
              color ="lightsteelblue1",
              fill="royalblue", alpha = 0.5) +
  geom_boxplot(aes(x = as.factor(Hour), y = temperature), 
               color = "firebrick2",
               width=0.3)
boxplot +
  scale_x_discrete(name = "Hour") + 
  scale_y_continuous(limits=c(-40,40), name = "Temperature (°C)") + 
  scale_fill_manual(values = c("#90C432","#2494b5")) +
  theme(panel.grid.major = element_line(colour = "gray", linetype = "dotted"), 
        panel.grid.minor = element_line(linetype = "blank"), 
        axis.title = element_text(size = 15,colour = "black"), 
        axis.text = element_text(colour = "black",size = 10), 
        panel.background = element_rect(fill = "white"), 
        plot.background = element_rect(colour = NA))
```

Air density
===

Row {data-width=100}
--------------------------------------
### Average Air Density
```{r, echo=FALSE}
air_bar <- round(mean(df2$air_density), digits = 2)
valueBox(value = air_bar,icon = "ion-ios-partlysunny",
         caption = "Average Air Density",color = "orange")
```

### Max Air Density
```{r, echo = FALSE}
airmax <- round(max(df2$air_density), digits = 2)
valueBox(value = airmax,icon = "ion-ios-partlysunny",
         caption = "Maximum Air Density",color = "blue")
```

### Min Air Density
```{r, echo = FALSE}
airmin <- round(min(df2$air_density), digits = 2)
valueBox(value = airmin,icon = "ion-ios-partlysunny",
         caption = "Minimum Air Density",color = "green")
```


Row 
-----------------------------------------------------------------------

### Annual Air Density Distribution 
```{r , echo=FALSE}
boxplot <- df2 %>% filter(Year < 2016) %>% 
  ggplot() + 
  geom_boxplot(aes(x = as.factor(Year), y = air_density), color = "dodgerblue2")
boxplot +
  scale_x_discrete(name = "Year") + 
  scale_y_continuous(limits=c(1,1.5),name = "Air density") + 
  scale_fill_manual(values = c("#90C432","#2494b5")) +
  theme(panel.grid.major = element_line(colour = "gray", linetype = "dotted"), 
        panel.grid.minor = element_line(linetype = "blank"), 
        axis.title = element_text(size = 15,colour = "black"), 
        axis.text = element_text(colour = "black",size = 10), 
        panel.background = element_rect(fill = "white"), 
        plot.background = element_rect(colour = NA))

```

### Monthly Air Density Distribution
```{r, echo=FALSE}
boxplot <- df2 %>% filter(Year < 2016) %>% 
  ggplot() + 
  geom_boxplot(aes(x = as.factor(Month), y = air_density), color = "dodgerblue2")
boxplot +
  scale_x_discrete(breaks = seq_along(month.name), 
                   labels = month.abb[1:12],
                   name = "Month") + 
  scale_y_continuous(limits=c(1,1.5), name = "Air density") + 
  scale_fill_manual(values = c("#90C432","#2494b5")) +
  theme(panel.grid.major = element_line(colour = "gray", linetype = "dotted"), 
        panel.grid.minor = element_line(linetype = "blank"), 
        axis.title = element_text(size = 15,colour = "black"), 
        axis.text = element_text(colour = "black",size = 10), 
        panel.background = element_rect(fill = "white"), 
        plot.background = element_rect(colour = NA))


```

### Hourly Air Density Distribution
```{r, echo=FALSE}
boxplot <- df2 %>% filter(Year < 2016) %>% 
  ggplot() + 
  geom_boxplot(aes(x = as.factor(Hour), y = air_density), color = "dodgerblue2")
boxplot +
  scale_x_discrete(name = "Hour") + 
  scale_y_continuous(limits=c(1,1.5), name = "Air density") + 
  scale_fill_manual(values = c("#90C432","#2494b5")) +
  theme(panel.grid.major = element_line(colour = "gray", linetype = "dotted"), 
        panel.grid.minor = element_line(linetype = "blank"), 
        axis.title = element_text(size = 15,colour = "black"), 
        axis.text = element_text(colour = "black",size = 10), 
        panel.background = element_rect(fill = "white"), 
        plot.background = element_rect(colour = NA))
```

Correlation Energy vs Weather (1)
===

Row
-----------------------------------------------------------------------
### November - April 
```{r , echo=FALSE}
graph <- function(data, mapping){
  p <- ggplot(data = data, mapping = mapping) + 
    geom_point(alpha = 0.5, color = "blue") + 
    geom_smooth(method = "lm", formula = y~x, col = 'red')
  p
}

plot_corr_par_mois <- function(df, months) {
  ggpairs(data = df[df$Month %in% months, ], 
          columns = c("Energy", "temperature", "air_density"),
          columnLabels = c("Energy", "Temp", "Air Density"),
          lower = list(continuous = graph)) +
          theme(axis.text = element_text(size = 5))
}

plot_corr_par_mois(df2, c(11, 12, 1, 2, 3, 4))
```

### May - October 
```{r, echo=FALSE}

plot_corr_par_mois(df2, c(5, 6, 7, 8, 9, 10))
```

Correlation (2)
===
Row
-----------------------------------------------------------------------
### November - April 
```{r, echo=FALSE}

plot_corr_par_mois <- function(df, months) {
  ggpairs(data = df[df$Month %in% months, ], 
          columns = c("Energy", "temperature", "irradiance_surface", 
                      "irradiance_toa"),
          columnLabels = c("Energy", "Temp",
                           "Irradiance", "Irradiance atm"),
          lower = list(continuous = graph)) +
          theme(axis.text = element_text(size = 5))
          
}

plot_corr_par_mois(df2, c(11, 12, 1, 2, 3, 4))
```

### May - October 
```{r, echo=FALSE}

plot_corr_par_mois(df2, c(5, 6, 7, 8, 9, 10))
```

Correlation (3)
===

Row
-----------------------------------------------------------------------
### November - April 
```{r, echo=FALSE}

plot_corr_par_mois <- function(df, months) {
  ggpairs(data = df[df$Month %in% months, ], 
          columns = c("Energy", "temperature", "precipitation", "snowfall", 
                      "snow_depth"),
          columnLabels = c("Energy", "Temp",
                           "Precipitation",
                           "Snow fall", "Snow depth"),
          lower = list(continuous = graph)) +
          theme(axis.text = element_text(size = 5))
}

plot_corr_par_mois(df2, c(11, 12, 1, 2, 3, 4))
```

### May - October 
```{r, echo=FALSE}

plot_corr_par_mois(df2, c(5, 6, 7, 8, 9, 10))
```
